var number1 = 9;
var number2 = 3;
var product = number1 * number2;
var charge = 10;
var payment = 5;
var amountRemaining = charge - payment;
var tests = 95;
var assignments = 90;
var final = 85;
var grade = (tests + assignments + final) / 3;
var firstName = 'Greg';
var lastName = ' Bailey';
var fullName = firstName + lastName;
var pH = 4;
var isAcidic = pH < 7;
var numberOfSoldiers = 5000;
var isSparta = (numberOfSoldiers === 300);
const nickname = fullName + ' is the GOAT!';
console.log(product);
console.log(typeof product);
console.log(amountRemaining);
console.log(typeof amountRemaining);
console.log(grade);
console.log(typeof grade);
console.log(fullName);
console.log(typeof fullName);
console.log(isAcidic);
console.log(typeof isAcidic);
console.log(isSparta);
console.log(typeof isSparta);
console.log(nickname);
console.log(typeof nickname);
